### ISSUE TITLE
aMapdoc is not defined

### ISSUE THREAD

**Issue by wspresto** [Esri/weighted-raster-overlay-service-toolbox#22]
Running script CreateWeightedOverlayMosaic...
 Exception occurred: name 'aMapdoc' is not defined
Completed script Create Weighted Overlay Mosaic...
 Failed to execute (CreateWeightedOverlayMosaic).

**Comment by wspresto** [comment]
Script assumes there is only one map in catalog for the project. 
ln 693:   m=p.listMaps("*")[0]  <---- bad assumption

Fails when multiple maps present in project.

**Comment by gudeso23** [comment]
Any solution?

**Comment by kennethWalton** [comment]
Hi @gudeso23 , would it be possible for you to share some test data and provide a list of reproducible steps for the issue you're seeing?

**Comment by gudeso23** [comment]
This error is not consistent but it happens some times when I try to update the rasters within my mosaic raster

**Comment by gudeso23** [comment]
@kennethWalton  Thanks for your reply, looks like after starting from scratch with only one map layout and two rasters it works fine.

**Comment by kennethWalton** [comment]
Fix is now available in the master branch.
