### ISSUE TITLE
RuntimeError: The row contains a bad value. [Title]

### ISSUE THREAD

**Issue by CatMcIlwraith** [Esri/weighted-raster-overlay-service-toolbox#29]
I'm trying to run the 'Create Weighted Overlay Mosaic' tool. The tool is consistently failing at line 890 with the error: RuntimeError: The row contains a bad value. [Title] (screenshot attached) Is there some additional processing that needs to be done on the input raster field names before the tool is run? Or is something else likely to be causing this issue? 

Many thanks.

![WRO error message](https://user-images.githubusercontent.com/81614789/167440233-c5eae997-86a3-4bc4-8dde-89e37673729f.PNG)

**Comment by kennethWalton** [comment]
Hi @CatMcIlwraith, the current version of the tool has a limit of the title being 50 characters. There are 2 possible workarounds until the tool is updated:
1. (Simplest workaround) Edit the name of the tif files so the name is less than 50 characters in length
2. If you're comfortable with making edits to the tool, you can do the following to increase the length of text allowed for the Title:
- Right click the "Create Weighted Overlay Mosaic" tool in the Contents panel, then select "Edit".
- Search for:
`('Title','String',50)`
then change it to the following:
`('Title','String',100)`
- Save the file
- Refresh the tool in the Catalog panel, then re-run tool

**Comment by CatMcIlwraith** [comment]
Brilliant, that seems to be working now. Thanks very much!
