### ISSUE TITLE
Unable to run Create Weighted Overlay Mosaic

### ISSUE THREAD

**Issue by littlelitz** [Esri/weighted-raster-overlay-service-toolbox#35]
Hi,
I have followed the readme instructions, but when I attempt to run the Create Weighted Overlay Mosaic, it fails instantly. I have pasted the dialogue box below. Any help on this would be extremely useful to me.
Here is a copy-paste of the text as well: 

Traceback (most recent call last):
  File "<string>", line 676, in execute
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1275, in Describe
    return gp.describe(value, data_type)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 384, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
RuntimeError: Object: Describe input value is not valid type

Traceback (most recent call last):
  File "<string>", line 676, in execute
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py", line 1275, in Describe
    return gp.describe(value, data_type)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 384, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
RuntimeError: Object: Describe input value is not valid type
Failed to execute (CreateWeightedOverlayMosaic).

![image](https://user-images.githubusercontent.com/13171285/228834065-1510c13e-2f71-4182-85b7-104470a6a13b.png)

Thank you,

**Comment by kennethWalton** [comment]
Hi @littlelitz , I haven't come across this specific error before, but it looks to be related to reading in your raster data.

I have a few questions:
1. Which version of ArcGIS Pro are you using?
2. Is this issue occurring will all of your data, or a specific raster?
3. Are you using GeoTiff rasters or a different format?

**Comment by littlelitz** [comment]
Hi @kennethWalton thank you for your reply!

I'm running ArcGIS Pro 3.0.3.

So, the Create Weighted Overlay Mosaic does not request a raster in its parameters, here is a screenshot from the tool window:
![image](https://user-images.githubusercontent.com/13171285/229103748-d2b46bb5-152e-4ba5-aa11-32dfa7ee2b6a.png)
It only requests the output geodatabase and a name for the mosaic dataset.

When the mosaic dataset is created, I was intending on adding GeoTiff rasters to it, although my raw data is netCDF files, which I was going to test adding as well, to see how multidimensional rasters affected the overlay. But, I can't get to that stage if the tool doesn't create a mosaic dataset.

Maybe there's something else I need to do before running the tool?

**Comment by kennethWalton** [comment]
Hi @littlelitz , have you taken a look at the following documentation?
https://doc.arcgis.com/en/geoplanner/latest/documentation/create-a-mosaic-dataset.htm

In ArcGIS Pro, did you add only the rasters to the Contents pane that you want to run the "Create a weighted overlay mosaic" tool against?

**Comment by littlelitz** [comment]
@kennethWalton my mistake, I did not see the documentation and didn't realize the tool used the existing rasters in the contents pane. The tool now works fine. Thank you for your help!

**Comment by kennethWalton** [comment]
@littlelitz Glad to hear it's working now, thanks!
