### ISSUE TITLE
Tool reports "No Changes Found" when changing Suitability Value in Arcpy

### ISSUE THREAD

**Issue by TheMapSmith** [Esri/weighted-raster-overlay-service-toolbox#37]
I am automating the process of creating and configuring a weighted raster overlay mosaic. Part of that process is copying the Python snippet that results from running the "Update WRO Layer Classification" tool. Once I successfully run the tool, I copy the Python snippet so that I can reuse it later if I have to change the source data or make other updates upstream. 

However, I notice that I'm not able to re-run the Python snippet, and the tool reports "No Changes Found" even when changes are in fact present. 

My current example, I'm wanting to revise the Suitability Value (weights) of multiple layers. I'd like to do that by changing the Suitability Value argument in the Python snippet, then re-run the cell. 

_Screenshot of part of my Jupyter notebook:_
![ArcGISPro_NkuDZqZAha](https://github.com/Esri/weighted-raster-overlay-service-toolbox/assets/8357118/a84eef26-89f7-40ca-bb89-7583270dd373)

However, whenever I do this via Arcpy I get the report "No Changes Found," even when I've changed the value in the snippet before re-running. 

I don't know why the behavior would be different using the Geoprocessing UI vs ArcPy, but it is. 

I have 5 WRO with 15-20 layers each that I'm wanting to streamline the creation and maintenance of, and this is causing me to jump out of my automation and use the UI for the ~100 layers I have to reconfigure. 

Can you please help me understand the best way to streamline this? Thanks! 

https://github.com/Esri/weighted-raster-overlay-service-toolbox/blob/45241121b5549832c6677682985aec9ff715aed3/WROS/Weighted%20Raster%20Overlay%20Service.pyt#L239-L257

**Comment by kennethWalton** [comment]
Hi @TheMapSmith, I haven't tried using Arcpy outside of the weighted overlay toolbox to run the tools. I'll have to take a look at this.

**Comment by TheMapSmith** [comment]
Thank you so much for a quick reply, Kenneth! If I can do anything to help you troubleshoot this, please don't hesitate to let me know! I'm happy to hop on a screen share or share my Jupyter notebook or ArcPro project if that's of use.

**Comment by kennethWalton** [comment]
@TheMapSmith We have a developer currently looking into the issue.

**Comment by vknoppkewetzel** [comment]
Hey @kennethWalton, do you have a timeline when the above PR fix will be implemented? Will it be soon or down the road? We are currently waiting on a fix to this issue to be able to move forward with building a variety of WROs for a project. thank you!

**Comment by kennethWalton** [comment]
Hi @vknoppkewetzel and @TheMapSmith - we have a potential fix in a branch here:
https://github.com/Esri/weighted-raster-overlay-service-toolbox/pull/38

I'll work on verifying and getting this merged today.

**Comment by vknoppkewetzel** [comment]
Awesome thanks @kennethWalton !

**Comment by kennethWalton** [comment]
Hi @vknoppkewetzel and @TheMapSmith - Fix has been merged and is now available in the "master" branch. Let me know if you're still running into issues. Thanks!

cc @nmpeterson
